name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop", "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/variable-substitution@v1
      with:
        files: 'auth.rs'
      env:
        CLIENTID: ${{ secrets.CLIENTID }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo clippy --verbose

  functional_test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/variable-substitution@v1
      with:
        files: 'src/auth.rs'
      env:
        CLIENTID: ${{ secrets.CLIENTID }}
    - name: cargo test
      run: cargo test --verbose
